// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SecondCuitRun
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UITestTargetVerknüpfunWindow UITestTargetVerknüpfunWindow
        {
            get
            {
                if ((this.mUITestTargetVerknüpfunWindow == null))
                {
                    this.mUITestTargetVerknüpfunWindow = new UITestTargetVerknüpfunWindow();
                }
                return this.mUITestTargetVerknüpfunWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITestTargetVerknüpfunWindow mUITestTargetVerknüpfunWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITestTargetVerknüpfunWindow : WinWindow
    {
        
        public UITestTargetVerknüpfunWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "TestTarget";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ConsoleWindowClass";
            this.WindowTitles.Add("TestTarget - Verknüpfung");
            this.WindowTitles.Add("Auswählen TestTarget - Verknüpfung");
            #endregion
        }
        
        #region Properties
        public WinClient UITestTargetVerknüpfunClient
        {
            get
            {
                if ((this.mUITestTargetVerknüpfunClient == null))
                {
                    this.mUITestTargetVerknüpfunClient = new WinClient(this);
                    #region Search Criteria
                    this.mUITestTargetVerknüpfunClient.SearchProperties[WinControl.PropertyNames.Name] = "TestTarget - Verknüpfung";
                    this.mUITestTargetVerknüpfunClient.WindowTitles.Add("TestTarget - Verknüpfung");
                    #endregion
                }
                return this.mUITestTargetVerknüpfunClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITestTargetVerknüpfunClient;
        #endregion
    }
}
